Remote builds: Bob needs to be trusted :/
See https://github.com/NixOS/nix/issues/2789

I thought using

    builder-use-substitutes = true

might be enough, and it seemed to work for whatever reason...
(Perhaps my config removing trust from bob was not fully
activated? Or perhaps I happened to have had all the necessary
derivations on tobati already.)

Anyway, these errors came back:

error: you are not privileged to build derivations
error: unexpected end-of-file

So switching back to the trusted user approach.