dev: -reason, Update nixpkgs
Removed reason because I'm not using it and it's also not
currently building in unstable:

    error: reason is not available for OCaml 4.13.1

Updated unstable to nixos-unstable because for whatever
reason that branch is currently ahead of nixos-unstable-small.

Specifically, nixos-unstable now has ff5975338afddaac7219ed5b7994ba01718ca3af
while nixos-unstable-small is still broken at 3c745c05fb1d0979af3c6db7dc8c12d35c7e41e0