wip Upgrade nixpkgs unstable
Set desktopManager.default explicitly as workaround for broken
backwards compatibility.

building Nix...
building the system configuration...
trace: Default graphical session, 'xmonad', not found.
Valid names for 'services.xserver.displayManager.defaultSession' are:
  xterm+xmonad
  xterm
  none+xmonad

error: while evaluating the attribute 'config.system.build.toplevel' at /etc/nixos/aij/unstable/nixos/modules/system/activation/top-level.nix:274:5:
while evaluating 'foldr' at /etc/nixos/aij/unstable/lib/lists.nix:52:20, called from /etc/nixos/aij/unstable/nixos/modules/system/activation/top-level.nix:138:12:
while evaluating 'fold'' at /etc/nixos/aij/unstable/lib/lists.nix:55:15, called from /etc/nixos/aij/unstable/lib/lists.nix:59:8:
while evaluating anonymous function at /etc/nixos/aij/unstable/nixos/modules/system/activation/top-level.nix:131:50, called from undefined position:
while evaluating the attribute 'assertion' at /etc/nixos/aij/unstable/nixos/modules/services/x11/display-managers/default.nix:347:9:
while evaluating the attribute 'displayManager.defaultSession' at undefined position:
while evaluating anonymous function at /etc/nixos/aij/unstable/lib/modules.nix:75:45, called from undefined position:
while evaluating the attribute 'value' at /etc/nixos/aij/unstable/lib/modules.nix:332:9:
while evaluating the option `services.xserver.displayManager.defaultSession':
while evaluating the attribute 'mergedValue' at /etc/nixos/aij/unstable/lib/modules.nix:364:5:
while evaluating anonymous function at /etc/nixos/aij/unstable/lib/modules.nix:364:32, called from /etc/nixos/aij/unstable/lib/modules.nix:364:19:
The option value `services.xserver.displayManager.defaultSession' in `/etc/nixos/aij/unstable/nixos/modules/services/x11/display-managers/default.nix' is not of type `session name'.

Ironically, defaultSessionFromLegacyOptions now requires the deprecated option
to be set... I'll debug that more shortly.